[package]
name = "uid-allocator"
version = "0.1.0"
edition = "2021"

[lib]
name = "uid_allocator"

[[bin]]
name = "uid-allocator"
path = "src/main.rs"


[dependencies]
rust-proto-new = {path = "../rust-proto-new", features=["uid-allocator-full"]}

chrono = "0.4.19"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }

maplit = "1.0.2"
tracing = "0.1.32"
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}
test-log = { version = "0.2.8", features = ["trace"] }
env_logger = "0.9.0"
async-recursion = "1.0.0"
rand = "0.8.5"
futures = "0.3.21"
itertools = "0.10.3"
prost = "0.9.0"
prost-types = "0.9.0"
tonic = "0.6.1"
sqlx = { version = "0.5.11", features = ["postgres", "runtime-tokio-rustls", "uuid", "offline"] }
thiserror = "1.0.30"
dashmap = "5.2.0"

[build-dependencies]
tonic-build = { version = "0.6.0", features = ["prost"] }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tracing-subscriber = "0.3.2"

[features]
