unstable_features = true

# Stable formatting directives
edition = "2018"
reorder_imports = true
reorder_modules = true

# Unstable formatting directives
group_imports = "StdExternalCrate"
imports_layout = "Vertical"
imports_granularity = "Crate"
