[package]
name = "generic-subgraph-generator"
version = "1.0.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"

[dependencies]
#graph-generator-lib = {path = "../graph-generator-lib/", version="*"}
grapl-graph-descriptions = { path="../../graph-descriptions", version="*"}
grapl-config = {path="../../grapl-config", version="*"}

sqs-executor = { path = "../../sqs-executor/" }
grapl-service = { path = "../../grapl-service/" }
grapl-observe = { path = "../../grapl-observe/" }
serde = "1"
serde_json = "1"
serde_derive = "1"
prost = "0.7"
log = "0"
regex = "1"
lazy_static = "1.2.0"

chrono = "0.4"
stopwatch = "0"

rusoto_s3 = { version="0.45.0", default_features = false, features=["rustls"] }
rusoto_core = { version="0.45.0", default_features = false, features=["rustls"] }
rusoto_sqs = { version="0.45.0", default_features = false, features=["rustls"] }

futures = "0.3.*"
aws_lambda_events = "0.2.0"
async-trait = "0.1.22"
zstd = "0.6"
tokio = { version = "0.2.*", features = ["sync", "rt-core", "macros", "time", "rt-threaded"] }

tracing = "0.1.15"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2"
eyre = "0.4.3"
thiserror = "1.0.23"
#openssl-probe = "0.1.2"


[dependencies.uuid]
version = "*"
features = ["v4"]
