[package]
name = "grapl-observe"
version = "0.0.1"
authors = ["Max Wittek <wimax@graplsecurity.com>"]
edition = "2018"
description = "Metrics and logging tooling for Grapl"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pin-project = "1.0"
chrono = "0.4"
lazy_static = "1"
log = "0.4"
regex = "1"
thiserror = "1"
dgraph-tonic = "0.9"
