[package]
name = "grapl-observe"
version = "0.0.1"
authors = ["Max Wittek <wimax@graplsecurity.com>"]
edition = "2018"
description = "Metrics and logging tooling for Grapl"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
lazy_static = "1.2.0"
log = "0.4.*"
regex = "1.1.0"
thiserror = "1.0.20"
dgraph-tonic = "0.8.4"
stopwatch = "0.0.7"
pin-project = "1.0.2"
