[package]
name = "grapl-web-ui"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "grapl-web-ui"

[features]
integration_tests = []

[dependencies]
actix-web = { version = "4.1", default_features = false, features = [
  "macros",
  "compress-brotli"
] }
awc = { version = "3", default_features = false, features = [
  "compress-brotli"
] }
actix-files = "0.6"
actix-session = "0.5"
actix-web-opentelemetry = { version = "0.12", features = ["awc"] }
argon2 = { version = "0.4", features = ["std"] }
chrono = { version = "0.4" }
hmap = "0.1"
futures-util = "0.3"
opentelemetry = { version = "0.17", features = ["rt-tokio"] }
rand = "0.8"
serde = "1"
serde_dynamodb = "0.9"
thiserror = "1.0"
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = "0.3"
url = "2.2"
grapl-config = { path = "../grapl-config" }
rusoto_core = { version = "0.47", default_features = false, features = [
  "rustls"
] }
rusoto_dynamodb = { version = "0.47", default_features = false, features = [
  "rustls"
] }
jsonwebtoken-google = "0.1"
secrecy = { version = "0.8", features = ["serde"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
rust-proto = { path = "../rust-proto" }
clap = { version = "3", default_features = false, features = [
  "std",
  "env",
  "derive"
] }
uuid = { version = "1.0", features = ["v4"] }
serde_json = "1"

[dev-dependencies]
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "cookies"
] }
eyre = "0.6"
