[package]
name = "grapl-utils"
version = "0.1.0"
authors = ["Nathanial Lattimer <nlattimer@graplsecurity.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-trait = "0.1.51"
tokio = { version = "1.17", features = ["time"] }
rusoto_core = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_dynamodb = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
