[package]
name = "sqs-executor"
version = "0.1.0"
authors = ["colin <colin@graplsecurity.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grapl-observe = { path = "../grapl-observe" }
grapl-utils = { path = "../grapl-utils" }

rusoto_core = {version = "0.46", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.46", default_features = false, features=["rustls"]}
rusoto_sqs = {version = "0.46", default_features = false, features=["rustls"]}

tokio = { version = "1", features = ["io-util", "sync", "rt", "macros", "time", "rt-multi-thread"] }

serde = "1.0"
serde_json = "1.0"
prost = "0.7"
thiserror = "1.0.22"
async-trait = "0.1"
tracing = "0.1.22"
tracing-futures = "0.2.4"
futures-util = "0.3.8"
uuid = {version = "0.8.1", features=["v4"]}
lazy_static = "1.4"
futures = "0.3.8"
darkredis = "0.8.0"
num_cpus = "1.13.0"
hex = "0.4.2"
tap = "1.0.0"
chrono = "0.4.19"
aws_lambda_events = "0.4"
stopwatch = "0.0.7"
lru = "0.6"
