[package]
name = "sqs-executor"
version = "0.1.0"
authors = ["colin <colin@graplsecurity.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
integration = []

[dependencies]
grapl-observe = { path = "../grapl-observe" }
grapl-utils = { path = "../grapl-utils" }
rust-proto = { path = "../rust-proto/" }
rusoto_core = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_s3 = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_sqs = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
tokio = { version = "1.14.0", features = [
  "io-util",
  "sync",
  "rt",
  "macros",
  "time",
  "rt-multi-thread"
] }
redis = { version = "0.21.4", features = ["tokio-comp", "connection-manager"] }
serde = "1.0.130"
serde_json = "1.0.72"
prost = "0.9.0"
thiserror = "1.0.30"
async-trait = "0.1.51"
tracing = "0.1.29"
tracing-futures = "0.2.5"
futures-util = "0.3"
uuid = { version = "0.8.2", features = ["v4"] }
lazy_static = "1.4.0"
futures = "0.3"
num_cpus = "1.13.0"
hex = "0.4.3"
tap = "1.0.1"
chrono = "0.4.19"
lru = "0.7.0"
itertools = "0.10.1"
