[package]
name = "kafka"
version = "0.1.0"
authors = ["Grapl, Inc. <sales@graplsecurity.com>"]
edition = "2021"
description = "Library for Grapl's Kafka services"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bytes = "1.1"
chrono = "0.4"
clap = { version = "3.0", default_features = false, features = [
  "std",
  "env",
  "derive"
] }
futures = "0.3"
rdkafka = { version = "0.28", features = [
  "cmake-build",
  "ssl",
  "gssapi-vendored",
  "tokio",
  "zstd-pkg-config"
] }
rust-proto = { path = "../rust-proto", version = "*" }
secrecy = "0.8.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["macros", "rt", "rt-multi-thread"] }
tracing = "0.1"
uuid = { version = "1.0", features = ["v4"], optional = true }

[features]
default = []
test-utils = ["uuid"]
