[package]
name = "osquery-subgraph-generator"
version = "0.1.0"
authors = ["Nathanial Lattimer <nlattimer@graplsecurity.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "osquery_subgraph_generator_lib"

[dependencies]
grapl-graph-descriptions = { path="../../graph-descriptions", version="*" }
endpoint-plugin = {path="../../endpoint-plugin"}
grapl-config = { path = "../../grapl-config", version="*" }
grapl-observe = { path = "../../grapl-observe", version="*" }
graph-generator-lib = { path="../graph-generator-lib", version="*" }
grapl-service = { path = "../../grapl-service" }
grapl-test = { path = "../../grapl-test", version = "*" }


sqs-executor = { path = "../../sqs-executor/" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
failure = "0.1.*"
log = "0.4.3"
regex = "1.3.9"

rusoto_s3 = {version="0.46.0", default_features = false, features=["rustls"]}
rusoto_core = {version="0.46.0", default_features = false, features=["rustls"]}
rusoto_sqs = {version="0.46.0", default_features = false, features=["rustls"]}

async-trait = "0.1.31"
zstd = "0.6"
tokio = { version = "1", features = ["sync", "rt", "macros", "time", "rt-multi-thread", "fs"] }
thiserror = "1.0.23"
tracing = "0.1.22"
