[package]
name = "graph-query-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rust-proto = { path = "../rust-proto" }
chrono = "0.4.19"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
maplit = "1.0.2"
tracing = "0.1.32"
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt"
] }
test-log = { version = "0.2.8", features = ["trace"] }
env_logger = "0.9.0"
scylla = "0.4.3"
rand = "0.8.5"
futures = "0.3.21"
itertools = "0.10.3"
prost = "0.9.0"
prost-types = "0.9.0"
tonic = "0.6.1"
thiserror = "1.0.31"
async-recursion = "1.0.0"
async-trait = "0.1.56"
moka = { version = "0.8.5", features = ["future"] }
rustc-hash = "1.1.0"
clap = { version = "3.2.13", features = ["std", "env", "derive"] }

[build-dependencies]
tonic-build = { version = "0.6.0", features = ["prost"] }

[features]
integration_tests = []
