[package]
name = "graph-query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bytes = "1.1"
rust-proto = { path = "../rust-proto" }
grapl-tracing = { path = "../grapl-tracing" }
chrono = "0.4.19"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt"
] }
test-log = { version = "0.2.8", features = ["trace"] }
env_logger = "0.9.0"
scylla = "0.4.3"
rand = "0.8.5"
futures = "0.3.21"
itertools = "0.10.3"
tonic = "0.6.1"
thiserror = "1.0.31"
async-recursion = "1.0.0"
async-trait = "0.1.56"
rustc-hash = "1.1.0"
clap = { version = "3.2.13", features = ["std", "env", "derive"] }
secrecy = "0.8.0"

[build-dependencies]
tonic-build = { version = "0.6.0", features = ["prost"] }

[dev-dependencies]
test-log = { version = "0.2", default-features = false, features = ["trace"] }
eyre = "0.6"

[features]
integration_tests = []
