[package]
name = "consul-connect"
version = "1.0.0"
authors = ["Max Wittek <wimax@graplsecurity.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.0", default_features = false, features = [
  "std",
  "env",
  "derive"
] }
thiserror = "1.0"
tokio = { version = "1.17", features = ["full"] }
tracing = "0.1"
trust-dns-resolver = "0.20"

[features]
client = []
