[package]
name = "grapl-config"
version = "0.0.1"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.*"
sqs-lambda = "0.20.*"

rusoto_s3 = { version="0.43.0", default_features = false, features=["rustls"] }
rusoto_core = { version="0.43.0", default_features = false, features=["rustls"] }
rusoto_sqs = { version="0.43.0", default_features = false, features=["rustls"] }

tracing = "0.1.15"
tracing-subscriber = "0.2.5"
tracing-futures = "0.2.4"
tokio = { version = "0.2.4", features = ["sync", "rt-core", "macros", "time", "rt-threaded"] }
color-eyre = "0.3.4"
eyre = "0.4.3"
