[package]
name = "metric-forwarder"
version = "0.0.1"
authors = ["Max Wittek <wimax@graplsecurity.com>"]
edition = "2018"

[dependencies]
grapl-config = {path="../grapl-config", version="*"}

async-trait = "0.1.22"
aws_lambda_events = "0.2.1"
base64 = "0.10.1"
chrono = "0.4.18"
flate2 = "1.0.6"
futures = "0.3.*"
hmap = "0.1.0"
itertools = "0.8.0"
lambda_runtime = "0.2.*"
log = "0.4.6"
ordered-float = "2.0.0"
rayon = "1.0.3"
rusoto_cloudwatch = { version="0.45.0", default_features = false, features=["rustls"] }
rusoto_core = { version="0.45.0", default_features = false, features=["rustls"] }
serde_json = "1.0.53"
statsd-parser = "0.3.0"
thiserror = "1.0.20"
tokio-compat = "0.1.*"
tokio = { version = "0.2.*", features = ["sync", "rt-core", "macros", "time", "rt-threaded"] }

[dependencies.uuid]
version = "*"
features = ["v4"]
