[package]
name = "metric-forwarder"
version = "0.0.1"
authors = ["Max Wittek <wimax@graplsecurity.com>"]
edition = "2018"

[dependencies]
grapl-config = { path = "../grapl-config", version = "*" }
async-trait = "0.1"
aws_lambda_events = "0.4"
base64 = "0.13"
chrono = "0.4"
flate2 = "1"
futures = "0.3"
lambda_runtime = "0.2"
log = "0.4"
ordered-float = "2"
rayon = "1.5"
rusoto_cloudwatch = { version = "0.46", default_features = false, features = [
  "rustls"
] }
rusoto_core = { version = "0.46", default_features = false, features = [
  "rustls"
] }
serde_json = "1"
statsd-parser = "0.3"
thiserror = "1"
tokio-compat = "0.1"
tokio = { version = "1", features = [
  "sync",
  "macros",
  "time",
  "rt-multi-thread"
] }
tokio-compat-02 = "0.2.0"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
hmap = "0.1"
itertools = "0.10"
