[package]
name = "sqs-lambda"
version = "0.21.1"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"
description = 'SQS Service helper library'
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grapl-observe = {path = "../grapl-observe"}

rusoto_core = {version = "0.45", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.45", default_features = false, features=["rustls"]}
rusoto_sqs = {version = "0.45", default_features = false, features=["rustls"]}

futures = { version = "0.3", features=["compat"] }

tokio = { version = "0.2", features = ["io-util", "sync", "macros", "time"] }
async-trait = "0.1"
serde = "1"
serde_json = "1"
prost = "0.7"
lambda_runtime = "0"

uuid = { version = "0", features = ["v4"] }
log = "0"
futures-retry = "0"
rand = "0"
rand_xorshift = "0"
hex = "0"
darkredis = "0"
num_cpus = "1"

aktors = "0"
derive-aktor = "0"

chrono = "0"
tracing = "0"
tracing-subscriber = "0"
tracing-futures = "0"

eyre = "0"
color-eyre = "0"
thiserror = "1"