[package]
name = "analyzer-dispatcher"
version = "1.0.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2021"

[dependencies]
rust-proto = { path = "../rust-proto", version = "*" }
grapl-config = { path = "../grapl-config", version = "*" }
grapl-observe = { path = "../grapl-observe" }
grapl-service = { path = "../grapl-service" }
futures = "0.3"
base64 = "0.13.0"
bytes = "1.1.0"
failure = "0.1.8"
log = "0.4.14"
prost = "0.9.0"
rusoto_s3 = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_core = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_sqs = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_credential = "0.47.0"
async-trait = "0.1.51"
zstd = "0.9.0"
tokio = { version = "1.14.0", features = [
  "sync",
  "rt",
  "macros",
  "time",
  "rt-multi-thread"
] }
chrono = "0.4.19"
sqs-executor = { path = "../sqs-executor/" }
thiserror = "1.0.30"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
uuid = { version = "0.8.2", features = ["v4"] }
