[package]
name = "graph-generator-lib"
version = "0.1.8"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"

[dependencies]
graph-descriptions = {package="grapl-graph-descriptions", version="*"}

failure = "0.1.*"

sha2 = "0.7.1"
rusoto_s3 = { version="0.43.0", default_features = false, features=["rustls"] }
rusoto_core = { version="0.43.0", default_features = false, features=["rustls"] }
rusoto_sqs = { version="0.43.0", default_features = false, features=["rustls"] }
grapl-config = { version="*" }

base64 = "0.9.2"
prost = "0.6.*"
serde_json = "1.0.53"
log = "0.4.3"
base16 = "0.1.1"
zstd = "0.5.1"
aws_lambda_events = "0.3.0"
sqs-lambda = "0.20.*"

lambda_runtime = "0.2.1"
chrono = "0.4.11"
serde = "1.0.110"
tokio-compat = "0.1.6"
rusoto_credential = "0.43.0"
tokio = "0.2.21"
