[package]
name = "rust-proto"
version = "0.1.0"
authors = ["Grapl, Inc. <sales@graplsecurity.com>"]
edition = "2021"
description = "Wrapper library for Grapl's protocol buffers"
license = "MIT"

[dependencies]
async-trait = "0.1"
bytes = "1.1"
clap = { version = "3.0", default_features = false, features = [
  "std",
  "env",
  "derive"
], optional = true }
client-executor = { path = "../client-executor" }
futures = "0.3"
rand = "0.8.5"
rustc-hash = "1.1.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.8" }
tonic-health = "0.6"
tracing = "0.1"
uuid = { version = "1.0", features = ["v4"] }

[build-dependencies]
tonic-build = { version = "0.8", features = ["prost-build"] }
prost-build = "0.11"

[dev-dependencies]
proptest = "1.0"
quickcheck = "1.0"
quickcheck_macros = "1.0"
test-context = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = ["client-factory"]
client-factory = ["clap"]
