[package]
name = "rust-proto"
version = "0.1.0"
authors = ["Grapl, Inc. <sales@graplsecurity.com>"]
edition = "2021"
description = "Wrapper library for Grapl's protocol buffers"
license = "MIT"

[dependencies]
async-trait = "0.1"
bytes = { workspace = true }
clap = { workspace = true }
client-executor = { path = "../client-executor" }
futures = "0.3"
grapl-utils = { path = "../grapl-utils" }
prost = "0.10"
rand = "0.8.5"
rustc-hash = "1.1.0"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.7", features = ["default", "compression", "tls"] }
tonic-health = "0.6"
tracing = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
prost-build = "0.10"
tonic-build = { version = "0.7", features = ["default", "compression"] }

[dev-dependencies]
eyre = { workspace = true }
proptest = "1.0"
quickcheck = "1.0"
quickcheck_macros = "1.0"
test-context = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = []
