[package]
name = "graph-mutation-service"
version = "0.1.0"
authors = ["colin <colin@graplsecurity.com>"]
edition = "2018"

[[bin]]
name = "graph-mutation-service"

[lib]
name = "graph_mutation_service_lib"

[dependencies]
anyhow = "1"
dgraph-tonic = { version = "0.9", features = ["dgraph-1-1"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-retry = "0.6"
grapl-config = { path="../grapl-config" }
grapl-graph-descriptions = { path="../graph-descriptions" }
grapl-observe = { path = "../grapl-observe" }
grapl-utils = { path = "../grapl-utils" }
lazy_static = "1.4"
lru = "0.6"
prost = "0.7"
prost-derive = "0.7"
rusoto_dynamodb = { version="0.46", default_features = false, features=["rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tonic = { version="0.4" }
tower = { version = "0.4" }
tracing = "0.1.*"
tracing-futures = "0.2.*"
tracing-subscriber = "0.2.*"
uuid = { version = "0.8", features=["v4"] }

[build-dependencies]
tonic-build = { version="0.4", features = ["prost"] }

[features]
integration = []
