[package]
name = "sysmon-parser"
version = "0.1.0-alpha.1"
authors = ["Grapl Security"]
description = "Type definitions and deserialization support for Sysmon events"
license = "MIT OR Apache-2.0"
keywords = ["sysinternals", "sysmon"]
edition = "2021"

[lib]
bench = false

[features]
default = ["serde"]
serde = ["dep:serde", "uuid/serde", "chrono/serde"]

[dependencies]
chrono = { version = "0.4", features = ["std"] }
derive-into-owned = "0.2"
memchr = "2"
thiserror = "1.0"
uuid = "0.8"
xmlparser = "0.13"
serde = { version = "1.0", default-features = false, features = [
  "derive"
], optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benches"
harness = false
