[package]
name = "plugin-executor"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "analyzer-executor"
path = "analyzer-executor.rs"

[[bin]]
name = "generator-executor"
path = "generator-executor.rs"

[lib]
name = "plugin_executor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-trait = "0.1"
clap = { version = "3.0", default_features = false, features = [
  "std",
  "env",
  "derive"
] }
generator-sdk = { path = "../plugin-sdk/generator-sdk", features = ["client"] }
grapl-config = { path = "../grapl-config" }
plugin-work-queue = { path = "../plugin-work-queue" }
rust-proto = { path = "../rust-proto" }
tokio = { version = "1.17", features = ["macros", "rt", "rt-multi-thread"] }
tracing = "0.1"

[features]
integration_tests = []
