name: Grapl Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - staging  # TODO: Delete after https://github.com/grapl-security/issue-tracker/issues/224
      - main

jobs:
  # NOTE: RtD will build and deploy our docs after-the-fact; but we'd like to prevent faulty
  # documentation from making its way into the source tree.
  ensure-docs-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run `docs/run_local.sh`
        run: |
          cd docs
          ./run_local.sh
